### ISSUE TITLE
How do I disable graph?

### ISSUE THREAD

**Issue by yankeexe** [michenriksen/hugo-theme-til#8]
Kudos on building such a neat site for TIL. 
However, for my use case, I want to disable the graph feature, is it possible?

**Comment by yankeexe** [comment]
Figured it out: 
```toml
[params]
showGraph = false
```

in hugo.toml.
